---
# List of users to create NFS mounts for
nfs_users:
  - bill

# NFS mounts for all workstations - Remove the placeholder _
nfs_mounts:
  - src: "192.168.86.90:/mnt/Data/books"
    dest: "/home/DEFAULT_USER/media/books"
    opts: "rw,comment=x-gvfs-hide"
  - src: "192.168.86.90:/mnt/Data/media/storage/movies"
    dest: "/home/DEFAULT_USER/media/movies"
    opts: "rw,comment=x-gvfs-hide"
  - src: "192.168.86.90:/mnt/Data/media/storage/tv"
    dest: "/home/DEFAULT_USER/media/tv"
    opts: "rw,comment=x-gvfs-hide"
  - src: "192.168.86.90:/mnt/Data/media/storage/music"
    dest: "/home/DEFAULT_USER/media/music"
    opts: "rw,comment=x-gvfs-hide"
  - src: "192.168.86.90:/mnt/Data/media/storage/photos"
    dest: "/home/DEFAULT_USER/media/photos"
    opts: "rw,comment=x-gvfs-hide"
  - src: "192.168.86.90:/mnt/Data/media/storage/home_videos"
    dest: "/home/DEFAULT_USER/media/home_videos"
    opts: "rw,comment=x-gvfs-hide"
  - src: "192.168.86.90:/mnt/ssd-files/home/DEFAULT_USER/Documents"
    dest: "/home/DEFAULT_USER/documents"
    opts: "rw,comment=x-gvfs-hide"
  - src: "192.168.86.90:/mnt/ssd-files/home/DEFAULT_USER/Downloads"
    dest: "/home/DEFAULT_USER/downloads"
    opts: "rw,comment=x-gvfs-hide"

# List of desired_directories
bill_directories:
  - "/home/bill/desktop"
  - "/home/bill/documents"
  - "/home/bill/downloads"
  - "/home/bill/media"
  - "/home/bill/code"
  - "/home/bill/git"

# List of unwanted directories
bill_unwanted_directories:
  - "/home/bill/Desktop"
  - "/home/bill/Documents"
  - "/home/bill/Downloads"
  - "/home/bill/Music"
  - "/home/bill/Pictures"
  - "/home/bill/Public"
  - "/home/bill/Templates"
  - "/home/bill/Videos"

# List of groups to create
groups_to_create:
  - media
  - docs
  - hal
  - ansible
  - data
  - git
  - librarian
