---
- name: Debug SMB Shares
  hosts: windows11
  gather_facts: no
  vars_files:
    - vault.yml
  
  tasks:
    - name: Check currently mapped drives
      win_shell: "net use"
      register: current_drives
      
    - name: Display currently mapped drives
      debug:
        msg: "{{ current_drives.stdout_lines }}"
    
    - name: Test access to each mapped drive
      win_shell: "dir {{ item.drive_letter }}"
      register: drive_access
      failed_when: false
      loop: "{{ windows_network_drives }}"
      
    - name: Display drive access results
      debug:
        msg: "Drive {{ item.item.drive_letter }} ({{ item.item.name }}): {{ 'ACCESSIBLE' if item.rc == 0 else 'NOT ACCESSIBLE - ' + (item.stderr | default('Unknown error')) }}"
      loop: "{{ drive_access.results }}"
      
    - name: List available shares on TrueNAS
      win_shell: "net view \\\\{{ truenas_server_ip }}"
      register: available_shares
      failed_when: false
      
    - name: Display available shares
      debug:
        msg: "Available shares on TrueNAS: {{ available_shares.stdout_lines if available_shares.rc == 0 else 'ERROR: ' + (available_shares.stderr | default('Unknown error')) }}"
