---
- name: Detailed Windows SMB Drive Diagnostics
  hosts: windows11
  gather_facts: no
  vars_files:
    - vault.yml
  
  tasks:
    - name: Clear all current drive mappings
      win_shell: "net use * /delete /yes"
      failed_when: false
      
    - name: Wait a moment for cleanup
      pause:
        seconds: 2
    
    - name: Test one drive at a time - Media drive
      win_shell: 'net use M: "\\192.168.86.109\media" "{{ truenas_smb_password }}" /user:{{ truenas_smb_user }} /persistent:yes'
      register: media_result
      failed_when: false
      
    - name: Show media drive result
      debug:
        msg: "Media drive mapping result: {{ media_result.stdout_lines if media_result.rc == 0 else 'FAILED: ' + (media_result.stderr | default('Unknown error')) }}"
    
    - name: Test media drive access immediately
      win_shell: "dir M:\\"
      register: media_access
      failed_when: false
      
    - name: Show media drive access
      debug:
        msg: "Media drive access: {{ 'SUCCESS' if media_access.rc == 0 else 'FAILED: ' + (media_access.stderr | default('Unknown error')) }}"
    
    - name: Check drive list after mapping
      win_shell: "net use"
      register: drives_after
      
    - name: Show drives after mapping
      debug:
        msg: "{{ drives_after.stdout_lines }}"
    
    - name: Try accessing via UNC path directly
      win_shell: 'dir "\\192.168.86.109\media"'
      register: unc_access
      failed_when: false
      
    - name: Show UNC access result
      debug:
        msg: "UNC path access: {{ 'SUCCESS' if unc_access.rc == 0 else 'FAILED: ' + (unc_access.stderr | default('Unknown error')) }}"
    
    - name: Check Windows PowerShell drives
      win_shell: "Get-PSDrive -PSProvider FileSystem"
      register: ps_drives
      failed_when: false
      
    - name: Show PowerShell drives
      debug:
        msg: "PowerShell drives: {{ ps_drives.stdout_lines }}"
