---
# tasks to complete before running roles
- hosts: all
  tags: always
  become: true
  vars_files:
    - ~/git/home.net/vault.yml
  pre_tasks:
    - name: pre-run | update package cache (debian, etc)
      tags: always
      apt: update_cache=yes
      changed_when: False
      when: ansible_distribution in ["Debian", "Ubuntu"]

    - name: Include host variables dynamically
      include_vars: "{{ item }}"
      with_items:
        - "host_vars/{{ inventory_hostname }}.yml"
      tags: always

# Common configuration for all hosts
- hosts: updates
  become: yes
  ignore_errors: yes
  force_handlers: yes
  vars:
    ansible_user: hal
  roles:
    - common

# Workstation configuration
- hosts: workstation
  ignore_unreachable: yes
  become: yes
  ignore_errors: yes
  force_handlers: yes
  vars:
    ansible_user: hal
  vars_files:
    - group_vars/workstations.yml
  roles:
    - workstation

# Local config (this will update SSH config with all hosts including Windows)
- hosts: local
  become: yes
  roles:
    - local

# LXC configuration
- hosts: lxc
  become: yes
  ignore_errors: yes
  force_handlers: yes
  vars:
    ansible_user: hal
  vars_files:    
    - group_vars/groups.yml
  roles:
    - lxc

# VM configuration
- hosts: vm
  become: yes
  ignore_errors: yes
  force_handlers: yes
  vars:
    ansible_user: hal
  roles:
    - vm

# Proxmox configuration
- hosts: proxmox_hosts
  become: yes
  ignore_errors: yes
  force_handlers: yes
  vars:
    ansible_user: hal
  roles:
    - proxmox_hosts

# Windows configuration
- hosts: windows
  gather_facts: no
  roles:
    - windows