---
# tasks to complete before running roles
- hosts: all
  tags: always
  become: true
  vars_files:
    - ~/git/home.net/vault.yml
  pre_tasks:
    - name: pre-run | update package cache (debian, etc)
      tags: always
      apt: 
        update_cache: yes
        force_apt_get: yes
      changed_when: False
      ignore_errors: yes
      when: ansible_distribution in ["Debian", "Ubuntu"] and not is_truenas | default(false)

    - name: Include host variables dynamically
      include_vars: "{{ item }}"
      with_items:
        - "host_vars/{{ inventory_hostname }}.yml"
      tags: always

# Common configuration for hosts that support it (all except Windows and TrueNAS)
- hosts: updates
  become: yes
  ignore_errors: yes
  force_handlers: yes
  vars:
    ansible_user: hal
  vars_files:
    - ~/git/home.net/vault.yml
    - group_vars/notifications.yml
  roles:
    - common
    - system_notifications

# Workstation configuration (common already applied via updates group)
- hosts: workstation
  ignore_unreachable: yes
  become: yes
  ignore_errors: yes
  force_handlers: yes
  vars:
    ansible_user: hal
  vars_files:
    - group_vars/workstations.yml
    - group_vars/notifications.yml
    - ~/git/home.net/vault.yml
  roles:
    - workstation

# Local config (common already applied via updates group)
- hosts: local
  become: yes
  vars_files:
    - group_vars/notifications.yml
  roles:
    - local

# LXC configuration (common already applied via updates group)
- hosts: lxc
  become: yes
  ignore_errors: yes
  force_handlers: yes
  vars:
    ansible_user: hal
  vars_files:    
    - group_vars/groups.yml
  roles:
    - lxc

# VM configuration (common already applied via updates group)
- hosts: vm
  become: yes
  ignore_errors: yes
  force_handlers: yes
  vars:
    ansible_user: hal
  roles:
    - vm

# Proxmox configuration (common already applied via updates group, limited by is_proxmox flag)
- hosts: proxmox_hosts
  become: yes
  ignore_errors: yes
  force_handlers: yes
  vars:
    ansible_user: hal
  vars_files:
    - ~/git/home.net/vault.yml
    - group_vars/notifications.yml
  roles:
    - proxmox_hosts

# TrueNAS configuration - minimal management
- hosts: truenas
  become: yes
  ignore_errors: yes
  force_handlers: yes
  vars_files:
    - ~/git/home.net/vault.yml
  roles:
    - truenas

# Windows configuration
- hosts: windows
  gather_facts: no
  vars_files:
    - ~/git/home.net/vault.yml
  roles:
    - windows