# tasks to complete before running roles
- hosts: workstations, server
  tags: always
  become: true
  vars_files:
    - ~/git/homelab/group_vars/vault.yml
  pre_tasks:
    - name: pre-run | update package cache (debian, etc)
      tags: always
      apt: update_cache=yes
      changed_when: False
      when: ansible_distribution in ["Debian", "Ubuntu"]

    - name: Include host variables dynamically
      include_vars: "{{ item }}"
      with_items:
        - "host_vars/{{ inventory_hostname }}.yml"
      tags: always