---
# tasks to complete before running roles
- hosts: all
  tags: always
  become: true
  vars_files:
    - ~/git/home.net/vault.yml
  pre_tasks:
    - name: pre-run | update package cache (debian, etc)
      tags: always
      apt: update_cache=yes
      changed_when: False
      when: ansible_distribution in ["Debian", "Ubuntu"] and not is_truenas | default(false)

    - name: Include host variables dynamically
      include_vars: "{{ item }}"
      with_items:
        - "host_vars/{{ inventory_hostname }}.yml"
      tags: always

# Common configuration for all hosts
- hosts: updates
  become: yes
  ignore_errors: yes
  force_handlers: yes
  vars:
    ansible_user: hal
  roles:
    - common

# Workstation configuration
- hosts: workstation
  ignore_unreachable: yes
  become: yes
  ignore_errors: yes
  force_handlers: yes
  vars:
    ansible_user: hal
  vars_files:
    - group_vars/workstations.yml
  roles:
    - workstation

# Local config (this will update SSH config with all hosts including Windows)
- hosts: local
  become: yes
  roles:
    - local

# LXC configuration
- hosts: lxc
  become: yes
  ignore_errors: yes
  force_handlers: yes
  vars:
    ansible_user: hal
  vars_files:    
    - group_vars/groups.yml
  roles:
    - lxc

# VM configuration
- hosts: vm
  become: yes
  ignore_errors: yes
  force_handlers: yes
  vars:
    ansible_user: hal
  roles:
    - vm

# Proxmox configuration
- hosts: proxmox_hosts
  become: yes
  ignore_errors: yes
  force_handlers: yes
  vars:
    ansible_user: hal
  roles:
    - proxmox_hosts

# TrueNAS configuration - minimal management
- hosts: truenas
  become: yes
  ignore_errors: yes
  force_handlers: yes
  vars_files:
    - ~/git/home.net/vault.yml
  tasks:
    - name: Load group variables
      include_vars: group_vars/groups.yml
      tags: always

    # Only manage bashrc files for bill and root
    - name: Copy bill's bashrc
      copy:
        src: roles/common/files/users/bill/bashrc
        dest: /home/bill/.bashrc
        owner: bill
        group: bill
        mode: '0644'
      tags: bill_bashrc

    - name: Copy root's bashrc
      copy:
        src: roles/common/files/users/root/bashrc
        dest: /root/.bashrc
        owner: root
        group: root
        mode: '0644'
      tags: root_bashrc

# Windows configuration
- hosts: windows
  gather_facts: no
  roles:
    - windows