---
- name: Windows SMB Environment Check
  hosts: windows11
  gather_facts: no
  vars_files:
    - vault.yml
  
  tasks:
    - name: Check Windows version
      win_shell: "(Get-WmiObject -Class Win32_OperatingSystem).Caption"
      register: windows_version
      
    - name: Show Windows version
      debug:
        msg: "Windows version: {{ windows_version.stdout | trim }}"
    
    - name: Check SMB client configuration
      win_shell: "Get-SmbClientConfiguration"
      register: smb_config
      failed_when: false
      
    - name: Show SMB client config
      debug:
        msg: "{{ smb_config.stdout_lines }}"
    
    - name: Check if SMB1 is enabled
      win_shell: "Get-WindowsOptionalFeature -Online -FeatureName SMB1Protocol"
      register: smb1_status
      failed_when: false
      
    - name: Show SMB1 status
      debug:
        msg: "{{ smb1_status.stdout_lines }}"
    
    - name: Check group policy settings for network drives
      win_shell: "gpresult /r /scope:user"
      register: group_policy
      failed_when: false
      
    - name: Show relevant group policy info
      debug:
        msg: "Group policy results: {{ group_policy.stdout_lines[-20:] }}"
    
    - name: Check if network location is set correctly
      win_shell: "Get-NetConnectionProfile"
      register: network_profile
      
    - name: Show network profile
      debug:
        msg: "{{ network_profile.stdout_lines }}"
    
    - name: Test basic network connectivity to TrueNAS SMB port
      win_shell: "Test-NetConnection -ComputerName 192.168.86.109 -Port 445"
      register: smb_port_test
      
    - name: Show SMB port test
      debug:
        msg: "{{ smb_port_test.stdout_lines }}"
