---
- name: Windows SMB User Context Test
  hosts: windows11
  gather_facts: no
  vars_files:
    - vault.yml
  
  tasks:
    - name: Clear all mappings
      win_shell: "net use * /delete /yes"
      failed_when: false
      
    - name: Check current user context
      win_shell: "whoami"
      register: current_user
      
    - name: Show current user
      debug:
        msg: "Current user: {{ current_user.stdout | trim }}"
    
    - name: Try using win_mapped_drive module instead
      win_mapped_drive:
        letter: M
        path: \\192.168.86.109\media
        username: "{{ truenas_smb_user }}"
        password: "{{ truenas_smb_password }}"
        state: present
      register: mapped_drive_result
      failed_when: false
      
    - name: Show mapped drive result
      debug:
        msg: "Mapped drive result: {{ mapped_drive_result }}"
    
    - name: Test drive access after win_mapped_drive
      win_shell: "Test-Path M:"
      register: test_path
      failed_when: false
      
    - name: Show test path result
      debug:
        msg: "Test-Path result: {{ test_path.stdout | trim }}"
    
    - name: If that worked, test directory listing
      win_shell: "Get-ChildItem M:"
      register: dir_list
      failed_when: false
      when: test_path.stdout | trim == "True"
      
    - name: Show directory listing
      debug:
        msg: "Directory listing: {{ dir_list.stdout_lines }}"
      when: test_path.stdout | trim == "True"
    
    - name: Check all drives again
      win_shell: "Get-PSDrive -PSProvider FileSystem"
      register: all_drives
      
    - name: Show all drives
      debug:
        msg: "{{ all_drives.stdout_lines }}"
