# test.yml
---
- name: Test SSH config for bill on a workstation
  hosts: desktop           # or use --limit
  gather_facts: yes
  vars:
    ansible_user: hal      # how Ansible *connects*
    ssh_config_user: bill  # who “owns” the SSH config and who gets the User: directive

  tasks:
    - name: Roll out only the ssh_config tasks
      include_role:
        name: workstation
        tasks_from: ssh_config
      tags: ssh_config      # if you still want to filter with --tags
