- hosts: dell
  become: yes
  vars_files:
    - group_vars/workstations.yml
  tasks:
    - name: Debug nfs_users
      debug:
        var: nfs_users

    - name: Debug nfs_mounts
      debug:
        var: nfs_mounts

    - name: Debug directory paths
      debug:
        msg: "Creating directory: {{ item.1 | replace('DEFAULT_USER', item.0) }}"
      with_nested:
        - "{{ nfs_users }}"
        - "{{ desired_directories }}"
