---
# Load vault variables for SSH keys
- name: Load vault variables
  include_vars: ~/git/home.net/vault.yml
  tags: always
  when: inventory_hostname == 'ha'

- name: Include NFS mount tasks
  include_tasks: nfs_mount.yml
  when: nfs_mounts is defined

- name: Create application user
  user:
    name: "{{ app_user }}"
    groups: "{{ app_user_groups | default([]) }}"
    append: yes
    shell: /bin/bash
    create_home: yes
  when: app_user is defined

- name: Create additional groups
  group:
    name: "{{ item }}"
    state: present
  loop: "{{ groups_to_create | default([]) }}"

- name: Install NVIDIA drivers (for GPU passthrough VMs)
  apt:
    name:
      - "nvidia-driver-{{ nvidia_driver_version | default('535') }}"
      - "nvidia-utils-{{ nvidia_driver_version | default('535') }}"
    state: present
    update_cache: yes
  when: 
    - gpu_passthrough is defined
    - gpu_passthrough | bool

- name: Setup unattended upgrades
  include_tasks: unattended_upgrades.yml
  when: unattended_upgrades is defined and unattended_upgrades | bool

- name: Setup SSH keys for Home Assistant root user
  block:
    - name: Ensure .ssh directory exists for root on Home Assistant
      file:
        path: "/root/.ssh"
        state: directory
        mode: '0700'
        owner: root
        group: root

    - name: Deploy SSH keys for root user on Home Assistant  
      authorized_key:
        user: root
        state: present
        key: "{{ item }}"
      loop: "{{ vault_bill_ssh_keys }}"
      no_log: true
  when: inventory_hostname == 'ha'
  tags: ha_ssh