---
- name: Download Google Chrome .deb package
  get_url:
    url: "https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb"
    dest: "/tmp/google-chrome-stable_current_amd64.deb"
    mode: '0644'
  when: chrome is defined and chrome | bool

- name: Install Google Chrome
  apt:
    deb: "/tmp/google-chrome-stable_current_amd64.deb"
    state: present
  when: chrome is defined and chrome | bool

- name: Fix any broken dependencies after Chrome installation
  apt:
    state: fixed
  when: chrome is defined and chrome | bool

- name: Set Chrome as default browser for each user
  become_user: "{{ item }}"
  command: xdg-settings set default-web-browser google-chrome.desktop
  loop: "{{ included_users }}"
  when: 
    - chrome is defined and chrome | bool
    - gnome is defined and gnome | bool
  environment:
    DISPLAY: ":0"

- name: Pin Chrome and Nautilus to dock/favorites for each user
  become_user: "{{ item }}"
  dconf:
    key: "/org/gnome/shell/favorite-apps"
    value: "['google-chrome.desktop', 'org.gnome.Nautilus.desktop', 'org.gnome.Terminal.desktop']"
    state: present
  loop: "{{ included_users }}"
  when: 
    - chrome is defined and chrome | bool
    - gnome is defined and gnome | bool

- name: Clean up Chrome .deb package
  file:
    path: "/tmp/google-chrome-stable_current_amd64.deb"
    state: absent
  when: chrome is defined and chrome | bool