- name: Add managed fstab entries
  blockinfile:
    path: /etc/fstab
    marker: "# {mark} ANSIBLE MANAGED BLOCK FOR NFS MOUNTS"
    block: |
      {% for user in nfs_users %}
      {% for mount in nfs_user_mounts %}
      {{ mount.src.replace('DEFAULT_USER', user) }} {{ mount.dest.replace('DEFAULT_USER', user) }} nfs {{ mount.opts }} 0 0
      {% endfor %}
      {% endfor %}
      {% for mount in nfs_specific_mounts %}
      {{ mount.src }} {{ mount.dest }} nfs {{ mount.opts }} 0 0
      {% endfor %}
      {% for mount in nfs_system_mounts %}
      {{ mount.src }} {{ mount.dest }} nfs {{ mount.opts }} 0 0
      {% endfor %}
    insertafter: EOF
    backup: yes

- name: Ensure NFS mount points exist
  file:
    path: "{{ item.dest }}"
    state: directory
    owner: root
    group: root
    mode: '0755'
  loop: "{{ nfs_system_mounts }}"

- name: Reload systemd daemon
  systemd:
    daemon_reload: yes
  become: true

- name: Remount all filesystems
  command: mount -a
  become: true
