---
- name: Ensure groups are created
  group:
    name: "{{ item.name }}"
    gid: "{{ item.gid }}"
    state: present
  with_items: "{{ group_definitions | selectattr('name', 'in', groups_to_create) | list }}"
  when: groups_to_create is defined

- name: Add hal to each nfs_user group
  user:
    name: hal
    groups: "{{ item }}"
    append: yes
  loop: "{{ nfs_users }}"
  run_once: true
  when: nfs_users is defined

- name: Ensure nfs_users are members of all created groups
  user:
    name: "{{ user }}"
    groups: "{{ groups_to_create | join(',') }}"
    append: yes
  loop: "{{ nfs_users }}"
  loop_control:
    loop_var: user
  when: groups_to_create is defined and nfs_users is defined
