# roles/workstation/tasks/ssh_config.yml
---

- name: Ensure .ssh dir exists for each user
  become: yes
  file:
    path: "/home/{{ item }}/.ssh"
    state: directory
    mode: '0700'
    owner: "{{ item }}"
    group: "{{ item }}"
  loop: "{{ ssh_config_user }}"
  tags: ssh_config

- name: Deploy aggregated SSH config for each user
  become: yes
  template:
    src: ssh_config.j2
    dest: "/home/{{ item }}/.ssh/config"
    mode: '0644'
    owner: "{{ item }}"
    group: "{{ item }}"
  loop: "{{ ssh_config_user }}"
  tags: ssh_config
