# roles/workstation/tasks/ssh_config.yml
---

- name: Ensure .ssh dir exists for {{ ssh_config_user }}
  become: yes
  file:
    path: "/home/{{ ssh_config_user }}/.ssh"
    state: directory
    mode: '0700'
    owner: "{{ ssh_config_user }}"
    group: "{{ ssh_config_user }}"
  tags: ssh_config

- name: Deploy aggregated SSH config for {{ ssh_config_user }}
  become: yes
  template:
    src: ssh_config.j2
    dest: "/home/{{ ssh_config_user }}/.ssh/config"
    mode: '0644'
    owner: "{{ ssh_config_user }}"
    group: "{{ ssh_config_user }}"
  tags: ssh_config
