- name: system setup | repositories | deploy sources.list from template
  tags: repositories
  template:
    src: sources.list.j2
    dest: /etc/apt/sources.list
    owner: root
    group: root
    mode: '0644'
    backup: yes
  notify: apt_update

- name: system setup | repositories | add debian-backports
  tags: backports,repositories
  apt_repository:
    repo: "deb http://deb.debian.org/debian {{ ansible_distribution_release }}-backports main"
    filename: debian-backports
  notify: apt_update
  when: ansible_distribution == "Debian" and
        ansible_distribution_release in ['buster', 'bullseye', 'bookworm']

- name: system setup | repositories | install package management tools (debian-based)
  tags: packages,system,settings
  package:
    name:
      - aptitude
      - software-properties-common
    state: latest
  when: ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]