---
# ntfy server configuration role

- name: Install ntfy
  get_url:
    url: https://github.com/binwiederhier/ntfy/releases/latest/download/ntfy_linux_amd64.tar.gz
    dest: /tmp/ntfy.tar.gz
    mode: '0644'

- name: Extract ntfy
  unarchive:
    src: /tmp/ntfy.tar.gz
    dest: /tmp
    remote_src: yes
    creates: /tmp/ntfy

- name: Install ntfy binary
  copy:
    src: /tmp/ntfy
    dest: /usr/local/bin/ntfy
    mode: '0755'
    remote_src: yes

- name: Create ntfy config directory
  file:
    path: /etc/ntfy
    state: directory
    mode: '0755'

- name: Create ntfy configuration
  template:
    src: server.yml.j2
    dest: /etc/ntfy/server.yml
    mode: '0644'
  notify: restart ntfy

- name: Create ntfy systemd service
  template:
    src: ntfy.service.j2
    dest: /etc/systemd/system/ntfy.service
    mode: '0644'
  notify:
    - reload systemd
    - restart ntfy

- name: Start and enable ntfy service
  systemd:
    name: ntfy
    state: started
    enabled: yes
