---
- name: Create Scripts directory if it doesn't exist
  win_file:
    path: "C:\\Scripts"
    state: directory
  tags: ['network_drives', 'scripts']

- name: Deploy network drive management PowerShell script
  win_copy:
    src: Map-NetworkDrives.ps1
    dest: "C:\\Scripts\\Map-NetworkDrives.ps1"
    backup: yes
  tags: ['network_drives', 'scripts']

- name: Create desktop shortcut for network drive script
  win_shortcut:
    src: "powershell.exe"
    dest: "C:\\Users\\{{ ansible_user }}\\Desktop\\Map Network Drives.lnk"
    arguments: "-ExecutionPolicy Bypass -File C:\\Scripts\\Map-NetworkDrives.ps1"
    description: "Map TrueNAS network drives"
    icon: "shell32.dll,137"
  tags: ['network_drives', 'scripts']

# Disabled until template variable resolution is fixed
# - name: Template and deploy updated script with current TrueNAS IP
#   win_template:
#     src: map-drives-config.ps1.j2
#     dest: "C:\\Scripts\\Map-NetworkDrives-Auto.ps1"
#     backup: yes
#   tags: ['network_drives', 'scripts']
#   when: truenas_server_ip is defined
