- name: Add managed fstab entries
  blockinfile:
    path: /etc/fstab
    marker: "# {mark} ANSIBLE MANAGED BLOCK FOR NFS MOUNTS"
    block: |
      {% for mount in nfs_mounts %}
      {{ mount.src }} {{ mount.dest }} nfs {{ mount.opts }} 0 0
      {% endfor %}
    insertafter: EOF
    backup: yes
  when: manage_nfs_mounts | default(true)

- name: Reload systemd daemon
  systemd:
    daemon_reload: yes
  become: true
  when: manage_nfs_mounts | default(true)

- name: Remount all filesystems
  command: mount -a
  become: true
  when: manage_nfs_mounts | default(true)
