---
# Load pve variables
- name: Load pve variables
  include_vars: host_vars/pve.yml
  tags: always

# Load group variables
- name: Load group variables
  include_vars: group_vars/groups.yml
  tags: always

- name: Load vault secrets
  include_vars: /home/bill/git/home.net/vault.yml
  tags: always

- include_tasks: groups.yml
- include_tasks: users.yml
- include_tasks: fstab.yml

- name: Install prerequisites
  ansible.builtin.import_tasks: prereq.yml
  when: pve_addons_enable_dark_theme and inventory_hostname != 'pbs'

- name: Enable Dark Theme
  ansible.builtin.import_tasks: install_dark_theme.yml
  when: pve_addons_enable_dark_theme and inventory_hostname != 'pbs'

- name: Removes Subscription Nag Box
  ansible.builtin.import_tasks: remove_subscription_nag.yml
  when: pve_addons_remove_subscription_nag and inventory_hostname != 'pbs'

- name: Remove enterprise repo
  ansible.builtin.import_tasks: remove_enterprise_repo.yml
  when: (pve_addons_remove_enterprise_repo or pve_addons_disable_enterprise_repo) and inventory_hostname != 'pbs'

- name: Add no subcription repo
  ansible.builtin.import_tasks: add_no_subscription_repo.yml
  when: pve_addons_add_no_subscription_repo and inventory_hostname != 'pbs'

- name: Force handlers to avoid apt error
  ansible.builtin.meta: flush_handlers

# Add provisioning setup
- name: Setup provisioning
  ansible.builtin.import_tasks: provisioning.yml
  when: enable_provisioning | default(true)
