---
- name: Ensure users are present on this workstation
  user:
    name: "{{ item.username }}"
    groups: "{{ item.groups | default([]) }}"
    append: yes
    uid: "{{ item.uid | default(omit) }}"
    shell: "{{ item.shell | default('/bin/bash') }}"
    state: "{{ item.state | default('present') }}"
    comment: "{{ item.comment | default(omit) }}"
    password: "{{ item.password | default(omit) }}"
  loop: "{{ users }}"
  loop_control:
    label: "{{ item.username }}"

- name: Ensure sudo is set for included users
  lineinfile:
    path: /etc/sudoers.d/{{ item.username }}
    create: yes
    mode: '0440'
    line: "{{ item.username }} ALL=(ALL) NOPASSWD:ALL"
  when: item.sudo | default(false)
  loop: "{{ users }}"
  loop_control:
    label: "{{ item.username }}"

- name: Set authorized keys for Bill from vault
  authorized_key:
    user: bill
    state: present
    key: "{{ item }}"
  loop: "{{ vault_bill_ssh_keys }}"
  no_log: true

- name: Copy bashrc for Bill
  copy:
    src: "/home/bill/git/home.net/roles/common/files/users/bill/bashrc"
    dest: "/home/bill/.bashrc"
    owner: bill
    group: bill
    mode: '0644'

- name: Copy bashrc for root
  copy:
    src: "/home/bill/git/home.net/roles/common/files/users/root/bashrc"
    dest: "/root/.bashrc"
    owner: root
    group: root
    mode: '0644'

- name: Add source ~/.bashrc to Bill's .bash_profile
  lineinfile:
    path: "/home/bill/.bash_profile"
    line: "source ~/.bashrc"
    create: yes
    owner: bill
    group: bill
    mode: '0644'

- name: Add source ~/.bashrc to root's .bash_profile
  lineinfile:
    path: "/root/.bash_profile"
    line: "source ~/.bashrc"
    create: yes
    owner: root
    group: root
    mode: '0644'

