---
# Home Assistant VM-204 Configuration
vm_id: 204
ansible_user: root
ansible_ssh_private_key_file: ~/.ssh/bill_ansible

# Platform-specific options
is_homeassistant: true
proxmox_instance: false

# Home Assistant specific settings
ha_config_path: /config
ha_version: "2025.6.3"

# SSH connection details
# Uses Advanced SSH & Web Terminal add-on
# Requires root user for SFTP support

# Server options - minimal management like TrueNAS
unattended_upgrades: false
web_server: false
docker: false
lxc: false

# Enable SSH key management
manage_ssh: true
manage_users: false
manage_packages: false
manage_services: false

# Disable mounts and groups
needed_mounts: []
groups_to_create: []
